name: Deploy to Azure App Service

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: coworking-reservation-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build with dotnet
      run: dotnet build --no-restore
    
    - name: Test with dotnet
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish with dotnet
      run: dotnet publish -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 